Repository openstack-k8s-operators/placement-operator, pull requests merged in 2024-02, with the labels that each got.

#140 [go.mod]Bump from v0.3.0 to pseudoversion
  go.mod
  go.sum
Labels: lgtm, approved

#143 Drop Debug fields
  api/bases/placement.openstack.org_placementapis.yaml
  api/v1beta1/placementapi_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/placement.openstack.org_placementapis.yaml
  config/samples/placement_v1beta1_placementapi.yaml
  config/samples/placement_v1beta1_placementtls.yaml
  pkg/placement/dbsync.go
  pkg/placement/deployment.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/placement_deploy_tls/03-assert.yaml
Labels: lgtm, approved

#146 Bump to latest mariadb-operator/api
  config/rbac/role.yaml
  controllers/placementapi_controller.go
  go.mod
  go.sum
  tests/functional/base_test.go
  tests/functional/placementapi_controller_test.go
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/placement_deploy_tls/03-assert.yaml
Labels: lgtm, approved

#147 [FIPS] build operator in fips mode
  .prow_ci.env
  Dockerfile
  Makefile
Labels: lgtm, approved

#148 Add missing logic for DefaultConfigOverwrite
  api/bases/placement.openstack.org_placementapis.yaml
  api/v1beta1/placementapi_types.go
  api/v1beta1/placementapi_webhook.go
  config/crd/bases/placement.openstack.org_placementapis.yaml
  controllers/placementapi_controller.go
  templates/placementapi/config/placement-api-config.json
  templates/placementapi/config/placement.conf
  tests/functional/placementapi_controller_test.go
  tests/functional/placementapi_webhook_test.go
Labels: lgtm, approved

#144 Controller runtime update
  .ci-operator.yaml
  .github/workflows/build-placement-operator.yaml
  Dockerfile
  api/bases/placement.openstack.org_placementapis.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/placementapi_webhook.go
  config/crd/bases/placement.openstack.org_placementapis.yaml
  controllers/placementapi_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: lgtm, approved, do-not-merge/hold

#150 Revert "Controller runtime update"
  .ci-operator.yaml
  .github/workflows/build-placement-operator.yaml
  Dockerfile
  api/bases/placement.openstack.org_placementapis.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/placementapi_webhook.go
  config/crd/bases/placement.openstack.org_placementapis.yaml
  controllers/placementapi_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: approved

#151 Controller runtime v0.16.4 Go 1.20
  .ci-operator.yaml
  .github/workflows/build-placement-operator.yaml
  Dockerfile
  Makefile
  api/bases/placement.openstack.org_placementapis.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/placementapi_webhook.go
  config/crd/bases/placement.openstack.org_placementapis.yaml
  controllers/placementapi_controller.go
  go.mod
  go.sum
  main.go
  tests/functional/suite_test.go
Labels: approved

#153 Bump to compatible deps
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved

#154 Fix mixing go.sum lines
  api/go.sum
Labels: approved

#155 Unique LeaderElectionID
  main.go
Labels: lgtm, approved

#156 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: lgtm, approved

#157 Bump golangci-lint
  .pre-commit-config.yaml
Labels: lgtm, approved

#158 [renovate]Remove golang constraint
  renovate.json
Labels: lgtm, approved

#166 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, approved

#165 [tlse] TLS database connection
  controllers/placementapi_controller.go
  go.mod
  go.sum
  templates/placementapi/config/placement-api-config.json
  templates/placementapi/config/placement-dbsync-config.json
  templates/placementapi/config/placement.conf
  tests/functional/placementapi_controller_test.go
Labels: lgtm, approved
